name: scan project

on: 
    push:
        branches: "main"
    
    jobs:
        scan:
            runs-on: ubuntu-latest
            steps:
                - name: Checkout code
                  uses: actions/checkout@v4